#!/usr/bin/env bash
#version 0.8

set -e

if ! git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
  echo "ERROR: you must execute this script from the OpenShift Git repository." 1>&2
  exit 1
fi

REPO_PATH="$(git config -f ~/.ocp-preview repo.name)"
USER="$(git config -f ~/.ocp-preview user.name)"
FILE_SERVER="$(git config -f ~/.ocp-preview server.name)"
CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
PAGES=$(git diff-tree HEAD HEAD~1 --no-commit-id --name-only -r | awk '!/modules\/(.*)\.adoc/' | awk '/(.*)\.adoc/' | cut -f 1 -d '.')
MODULES=$(git diff-tree HEAD HEAD~1 --no-commit-id --name-only -r | awk '/modules\/(.*)\.adoc/')

#use the asciibinder container
ASCIIBINDER="podman run --rm -it -v `pwd`:/docs:Z quay.io/openshift-cs/asciibinder asciibinder"

cd $REPO_PATH

DISTRO=$2

if [[ -z "$DISTRO" ]]; then
    DISTRO="openshift-enterprise"
  elif [[ "$2" = "all" ]]; then
    echo "Building all distros..."
    DISTRO=""
  else
   echo "Building $2 distro..."
   DISTRO="$2"
fi

function full_build {
  $ASCIIBINDER build -d $DISTRO; echo "Running rsync..."; rsync_build; echo "...rsync run complete!"

  xdg-open >/dev/null 2>&1 http://$FILE_SERVER/$USER/$CURRENT_BRANCH/welcome/index.html
  echo "Check the docs at: http://$FILE_SERVER/$USER/$CURRENT_BRANCH/welcome/index.html"
}

function refresh_build {
  if [[ -z "$PAGES" ]]; then
    for MODULE in $MODULES
      do UPDATED_PAGES=$(find . -name "*.adoc" -type f -exec grep -l "$MODULE" {} \; | sed 's|^\./||' | sed 's|\.adoc||' )
        for PAGE in $UPDATED_PAGES
          do $ASCIIBINDER build --page=$PAGE; echo "Running rsync for $PAGE..."; rsync_build; echo "...rsync run complete!"
          echo "Check the docs at: http://$FILE_SERVER/$USER/$CURRENT_BRANCH/$PAGE.html"
        done
    done
  else
    for PAGE in $PAGES
      do $ASCIIBINDER build --page=$PAGE; echo "Running rsync for $PAGE..."; rsync_build; echo "...rsync run complete!" 
      echo "Check the docs at: http://$FILE_SERVER/$USER/$CURRENT_BRANCH/$PAGE.html"
    done
  fi
}

function rsync_build {
  rsync -auzq --rsync-path="mkdir -p ~/public_html/$CURRENT_BRANCH && rsync" --progress _preview/$DISTRO/$CURRENT_BRANCH/* $USER@$FILE_SERVER:~/public_html/$CURRENT_BRANCH
}

function local_full_build {
  $ASCIIBINDER clean; $ASCIIBINDER build -d $DISTRO
  xdg-open >/dev/null 2>&1 $REPO_PATH/_preview/$DISTRO/$CURRENT_BRANCH/welcome/index.html
  echo "Check the docs at: $REPO_PATH/_preview/$DISTRO/$CURRENT_BRANCH/welcome/index.html"
}

function local_refresh_build {
  if [[ -z "$PAGES" ]]; then
    echo "Oop! There are no assemblies in this PR, run a full build instead..."
  else
    for PAGE in $PAGES
      do $ASCIIBINDER build --page=$PAGE
      echo "Check the docs at: $REPO_PATH/_preview/$DISTRO/$CURRENT_BRANCH/welcome/index.html"
    done
  fi
}

function delete_build {
  ssh $USER@$FILE_SERVER 'rm -rf ~/public_html/$CURRENT_BRANCH'
  echo 'Deleted the' $CURRENT_BRANCH 'build from' $FILE_SERVER'.'
}

function show_help {
  echo "Usage: ocp-preview [OPTION] [DISTRO]"
  echo "Usage: [DISTRO] is optional, build default is openshift-enterprise. Specify 'all' to build all distros."
  echo "-b, --build"
  echo "               does a full clean build and rsync."
  echo "-l, --local-build"
  echo "               does a full clean build locally, does not rsync."
  echo "-r, --refresh"
  echo "               builds and rsyncs updated files only."
  echo "-f, --local-refresh"
  echo "               builds updated files locally, does not rsync."
  echo "-d, --delete"
  echo "               deletes the current pull request build from the file server."
}

if [ "$1" = "--build" -o "$1" = "-b" ]; then
  full_build
elif [ "$1" = "--refresh" -o "$1" = "-r" ]; then
  refresh_build
elif [ "$1" = "--local-build" -o "$1" = "-l" ]; then
  local_full_build
elif [ "$1" = "--local-refresh" -o "$1" = "-f" ]; then
  local_refresh_build
elif [ "$1" = "--delete" -o "$1" = "-d" ]; then
  delete_build
elif [ "$1" = "--help" -o "$1" = "-h" ]; then
  show_help 
elif [[ ! $@ =~ ^\-.+ ]]; then
  show_help
else
  break
fi
